#!/bin/bash
# setup_fastdds.sh
#
# Generates FastDDS profiles for ROS2 communication via Discovery Server.
# Restricts transport to specified interfaces to prevent GigE camera IPs
# (169.254.x.x) from being advertised as data locators.
#
# Usage:
#   ./setup_fastdds.sh publisher <interface> [<extra_interface>]
#   ./setup_fastdds.sh subscriber <interface>
#
# Examples:
#   ./setup_fastdds.sh publisher wt0          # VPN only (+ loopback auto)
#   ./setup_fastdds.sh publisher wt0 wlan0    # VPN + WiFi (+ loopback auto)
#   ./setup_fastdds.sh subscriber wt0         # Notebook via VPN
#
# Discovery Server env vars (set separately):
#   Publisher:  export ROS_DISCOVERY_SERVER=127.0.0.1:11811
#   Subscriber: export ROS_DISCOVERY_SERVER=<publisher_vpn_ip>:11811

set -e

MODE="$1"
INTERFACE="$2"
EXTRA_INTERFACE="$3"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
    echo "Usage: $0 {publisher|subscriber} <interface> [<extra_interface>]"
    echo ""
    echo "Examples:"
    echo "  $0 publisher wt0          # Netbird VPN (loopback added automatically)"
    echo "  $0 publisher wt0 wlan0    # VPN + WiFi"
    echo "  $0 subscriber wt0         # Notebook via VPN"
    echo ""
    echo "Available interfaces:"
    ip -4 addr show | awk '/^[0-9]+:/{iface=$2} /inet /{print "  " iface, $2}' | grep -v '127.0.0.1'
}

if [[ -z "$MODE" || -z "$INTERFACE" ]]; then
    usage
    exit 1
fi

if [[ "$MODE" != "publisher" && "$MODE" != "subscriber" ]]; then
    echo "Error: mode must be 'publisher' or 'subscriber'"
    usage
    exit 1
fi

get_ip() {
    local iface="$1"
    ip -4 addr show "$iface" 2>/dev/null | grep -oP '(?<=inet )\d+\.\d+\.\d+\.\d+' | head -1
}

IP=$(get_ip "$INTERFACE")
if [[ -z "$IP" ]]; then
    echo "Error: no IPv4 address found on interface '$INTERFACE'"
    usage
    exit 1
fi

EXTRA_IP=""
if [[ -n "$EXTRA_INTERFACE" ]]; then
    EXTRA_IP=$(get_ip "$EXTRA_INTERFACE")
    if [[ -z "$EXTRA_IP" ]]; then
        echo "Warning: no IPv4 on '$EXTRA_INTERFACE', ignoring"
    fi
fi

write_publisher_profile() {
    local output="$1"
    local ip="$2"
    local extra_ip="$3"

    # Build whitelist and locator entries
    local whitelist="        <address>127.0.0.1</address>
        <address>${ip}</address>"
    local locators="        <locator>
          <udpv4><address>127.0.0.1</address><port>0</port></udpv4>
        </locator>
        <locator>
          <udpv4><address>${ip}</address><port>0</port></udpv4>
        </locator>"

    if [[ -n "$extra_ip" ]]; then
        whitelist="${whitelist}
        <address>${extra_ip}</address>"
        locators="${locators}
        <locator>
          <udpv4><address>${extra_ip}</address><port>0</port></udpv4>
        </locator>"
    fi

    local extra_comment=""
    if [[ -n "$extra_ip" ]]; then
        extra_comment="
    - ${extra_ip} : interface ${EXTRA_INTERFACE}"
    fi

    cat > "$output" << XMLEOF
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  FastDDS Publisher Profile — Discovery Server mode
  Generated by: ./setup_fastdds.sh publisher ${INTERFACE} ${EXTRA_INTERFACE}

  Transport restrito a:
    - 127.0.0.1 : comunicacao local (resizer, discovery server)
    - ${ip} : interface ${INTERFACE}${extra_comment}

  Impede interfaces GigE (169.254.x.x) de serem anunciadas como locators.
  Discovery gerenciado por ROS_DISCOVERY_SERVER env var.

  === CARRO ===
  Regenerar com a interface do carro:
    ./setup_fastdds.sh publisher <car_lan_interface>
-->
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <transport_descriptors>
    <transport_descriptor>
      <transport_id>restricted_udp</transport_id>
      <type>UDPv4</type>
      <interfaceWhiteList>
${whitelist}
      </interfaceWhiteList>
    </transport_descriptor>
  </transport_descriptors>
  <participant profile_name="default" is_default_profile="true">
    <rtps>
      <userTransports>
        <transport_id>restricted_udp</transport_id>
      </userTransports>
      <useBuiltinTransports>false</useBuiltinTransports>
      <defaultUnicastLocatorList>
${locators}
      </defaultUnicastLocatorList>
    </rtps>
  </participant>
</profiles>
XMLEOF
    echo "Generated: $output"
    echo "  Loopback: 127.0.0.1"
    echo "  Interface: $INTERFACE -> $ip"
    [ -n "$extra_ip" ] && echo "  Extra: $EXTRA_INTERFACE -> $extra_ip"
}

write_subscriber_profile() {
    local output="$1"
    local ip="$2"

    cat > "$output" << XMLEOF
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  FastDDS Subscriber Profile — Discovery Server mode
  Generated by: ./setup_fastdds.sh subscriber ${INTERFACE}

  Transport restrito a ${ip} (${INTERFACE}).
  Discovery gerenciado por ROS_DISCOVERY_SERVER env var.

  === CARRO ===
  Regenerar com a interface do carro:
    ./setup_fastdds.sh subscriber <car_lan_interface>
-->
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <transport_descriptors>
    <transport_descriptor>
      <transport_id>restricted_udp</transport_id>
      <type>UDPv4</type>
      <interfaceWhiteList>
        <address>${ip}</address>
      </interfaceWhiteList>
    </transport_descriptor>
  </transport_descriptors>
  <participant profile_name="default" is_default_profile="true">
    <rtps>
      <userTransports>
        <transport_id>restricted_udp</transport_id>
      </userTransports>
      <useBuiltinTransports>false</useBuiltinTransports>
      <defaultUnicastLocatorList>
        <locator>
          <udpv4>
            <address>${ip}</address>
            <port>0</port>
          </udpv4>
        </locator>
      </defaultUnicastLocatorList>
    </rtps>
  </participant>
</profiles>
XMLEOF
    echo "Generated: $output"
    echo "  Interface: $INTERFACE -> $ip"
}

if [[ "$MODE" == "publisher" ]]; then
    write_publisher_profile "$SCRIPT_DIR/fastdds_publisher.xml" "$IP" "$EXTRA_IP"
    echo ""
    echo "Set in your environment:"
    echo "  export FASTRTPS_DEFAULT_PROFILES_FILE=$SCRIPT_DIR/fastdds_publisher.xml"
    echo "  export ROS_DISCOVERY_SERVER=127.0.0.1:11811"
elif [[ "$MODE" == "subscriber" ]]; then
    write_subscriber_profile "$SCRIPT_DIR/fastdds_subscriber.xml" "$IP"
    echo ""
    echo "Set in your environment:"
    echo "  export FASTRTPS_DEFAULT_PROFILES_FILE=$SCRIPT_DIR/fastdds_subscriber.xml"
    echo "  export ROS_DISCOVERY_SERVER=<publisher_vpn_ip>:11811"
fi
