#!/bin/bash
# setup_fastdds.sh
#
# Generates FastDDS unicast profiles for multi-machine ROS2 communication.
# Required when multiple network interfaces are present (e.g., GigE camera
# interface + WiFi), to prevent FastDDS from advertising the wrong IP.
#
# Run this on each machine before starting the camera node or receiver.
#
# Usage:
#   ./setup_fastdds.sh publisher <interface>   # on the camera machine
#   ./setup_fastdds.sh subscriber <interface>  # on the receiver machine
#
# Example:
#   ./setup_fastdds.sh publisher wlan0
#   ./setup_fastdds.sh subscriber eth0
#
# The generated profile restricts FastDDS unicast locators to the specified
# interface IP. Multicast discovery (239.255.0.1) is preserved.
#
# To find your interface names: ip link show

set -e

MODE="$1"
INTERFACE="$2"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
    echo "Usage: $0 {publisher|subscriber} <interface>"
    echo ""
    echo "Examples:"
    echo "  $0 publisher wlan0     # WiFi interface on camera machine"
    echo "  $0 subscriber eth0     # LAN interface on receiver machine"
    echo ""
    echo "Available interfaces:"
    ip -4 addr show | awk '/^[0-9]+:/{iface=$2} /inet /{print "  " iface, $2}' | grep -v '127.0.0.1'
}

if [[ -z "$MODE" || -z "$INTERFACE" ]]; then
    usage
    exit 1
fi

if [[ "$MODE" != "publisher" && "$MODE" != "subscriber" ]]; then
    echo "Error: mode must be 'publisher' or 'subscriber'"
    usage
    exit 1
fi

# Get IP from interface
IP=$(ip -4 addr show "$INTERFACE" 2>/dev/null | grep -oP '(?<=inet )\d+\.\d+\.\d+\.\d+' | head -1)

if [[ -z "$IP" ]]; then
    echo "Error: no IPv4 address found on interface '$INTERFACE'"
    echo ""
    usage
    exit 1
fi

write_profile() {
    local output="$1"
    local ip="$2"
    local role="$3"

    cat > "$output" << EOF
<?xml version="1.0" encoding="UTF-8" ?>
<!-- FastDDS unicast profile for the ${role}.
     Generated by setup_fastdds.sh — do not commit this file.
     Regenerate with: ./setup_fastdds.sh ${MODE} ${INTERFACE}

     Restricts FastDDS to announce only the specified interface IP,
     preventing other interfaces from being advertised as data locators.
     Multicast discovery (239.255.0.1) is preserved (no <builtin> block).
-->
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <participant profile_name="default_participant" is_default_profile="true">
    <rtps>
      <defaultUnicastLocatorList>
        <locator>
          <udpv4>
            <address>${ip}</address>
            <port>0</port>
          </udpv4>
        </locator>
      </defaultUnicastLocatorList>
    </rtps>
  </participant>
</profiles>
EOF
    echo "Generated: $output"
    echo "  Interface: $INTERFACE  IP: $ip"
}

if [[ "$MODE" == "publisher" ]]; then
    write_profile "$SCRIPT_DIR/fastdds_publisher.xml" "$IP" "publisher (camera machine)"
    # Legacy alias
    cp "$SCRIPT_DIR/fastdds_publisher.xml" "$SCRIPT_DIR/fastdds_multipc.xml"
    echo "  Also updated: fastdds_multipc.xml (legacy alias)"
elif [[ "$MODE" == "subscriber" ]]; then
    write_profile "$SCRIPT_DIR/fastdds_subscriber.xml" "$IP" "subscriber (receiver machine)"
    # Legacy alias
    cp "$SCRIPT_DIR/fastdds_subscriber.xml" "$SCRIPT_DIR/fastdds_receiver.xml"
    echo "  Also updated: fastdds_receiver.xml (legacy alias)"
fi

echo ""
echo "Done. Set the environment variable in your shell or scripts:"
if [[ "$MODE" == "publisher" ]]; then
    echo "  export FASTRTPS_DEFAULT_PROFILES_FILE=$SCRIPT_DIR/fastdds_publisher.xml"
else
    echo "  export FASTRTPS_DEFAULT_PROFILES_FILE=$SCRIPT_DIR/fastdds_subscriber.xml"
fi
